### ISSUE TITLE
feat: export profile as JSON file

### ISSUE THREAD

**Issue by ajhalili2006** [amitojsingh366/easy-rpc#2]
## Current Situation

When I export it using the Export to clipboard way, some syntax errors are being fired up in console:

![image](https://user-images.githubusercontent.com/34998342/126896532-269f141f-f408-4e72-bc97-917ca989f1ff.png)

## Recommendation

Just show the File Save prompt so user can save that profile an simple JSON file. Also bring support to import from JSON file by the way.

**Comment by amitojsingh366** [comment]
implemented in 419e1300d084bc572bb13d026469e5c705bf92ed
